export const CREATE_COURSE =  'CREATE_COURSE';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSE_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHOR_SUCCESS';
export const CREATE_AUTHORS_SUCCESS = 'CREATE_AUTHORS_SUCCESS';
export const UPDATE_AUTHORS_SUCCESS = 'UPDATE_AUTHORS_SUCCESS';
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const DELETE_COURSE_OPTIMISTIC = 'DELETE_COURSE_OPTIMISTIC';
